# Generated by Django 5.1.4 on 2024-12-31 20:56

import authentications.managers.authentication
import authentications.managers.user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Email address used for user identification.', max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Indicates whether the user has superuser privileges.')),
                ('is_staff', models.BooleanField(default=False, help_text='Indicates whether the user has staff privileges.')),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (2, 'Not Active')], default=1, help_text='User account status')),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Normal'), (3, 'Manager')], default=2, help_text='User type')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Time when the user account was created.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the user account is deleted.')),
                ('deletion_date', models.DateTimeField(blank=True, editable=False, help_text='Time when the user account was deleted', null=True)),
            ],
            options={
                'db_table': 'account',
            },
            managers=[
                ('objects', authentications.managers.user.UserManager()),
                ('all_objects', authentications.managers.authentication.AuthenticationUserManager()),
            ],
        ),
    ]
