# Generated by Django 5.1.4 on 2024-12-31 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255)),
                ('quantity', models.PositiveIntegerField(help_text='The quantity of the product available in stock.')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='The total price of the product (e.g., in USD).', max_digits=10)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether the product is deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the product was last updated.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='The date and time when the product was deleted.', null=True)),
                ('owner', models.ForeignKey(help_text='The user who owns this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
